### ISSUE TITLE
SVG editor on base of luigi

### ISSUE THREAD

**Issue by RimeOCRLIB** [nakst/luigi#23]
Good day.
Thank you for your generous contribution to open source community.

For OCR training and asian fonts development we need implement editable base SVG shapes on base of luigi. Reslts we will be happy to share.

After page OCR in training mode it is need edit about thousand of restangles on every OCR page - need to know size and position after element edition with mouse  and set unicode name of element. HTML just freeze on this task.

Which UI_Element you think may give us a correct start?
UIMDIClientCreate look most suitable but it will be need make it more light - close active element by keyboard and common button for example. No need close button on small shape.
Will be happy to any advice.
Alexander

**Comment by RimeOCRLIB** [comment]
For start we add UIUnit with custom paint and update. This unit we may use to draw editable svg. Will keep you informed on progress.
Another point we need display pages with about 700 small letter images with addition info as OCR font table. It is no need pan and zoom in that images so we start base UIImage element with initial position, but no pun and zoom route.

**Comment by nakst** [comment]
Writing a vector graphic editor is a difficult task, so there is not much I can advise you on. 
However I did write something similar here using Luigi: https://gitlab.com/nakst/essence/-/blob/master/util/designer2.cpp?ref_type=heads.
Maybe this will be of help. But please note that the license for this source code is different to that of Luigi.

**Comment by RimeOCRLIB** [comment]
Thank you for your answer. We may add svg support for designer2 editor later.
For first steps we need to setup base routes for object handling in main window.
UI_MSG_FIND_BY_POINT will be heavy if manage many objects in window.
Even if we will use outer object manager problem will be the same.
Usual ocr string with text letters hypothesis is about 3000 objects per string of ierogliphic text. In ocr we use array of projections of letters objects on X axis. Search in that array is reasonable fast. We my think about better solution.

**Comment by RimeOCRLIB** [comment]
Thank you for your answer and all your beautifull work with Essence. 
We may add svg support for designer2 editor later.
For first steps we need to setup base routes for object handling in main window.

1. UI_MSG_FIND_BY_POINT in linked list will be heavy if manage many objects in window.
Even if we will use outer object manager problem will be the same.
For example usual ocr string with text letters hypothesis is about 3000 objects per string of ierogliphic text. In ocr we use array of projections of letters objects on X axis. Search in that array is reasonable fast. We my think about better solution.

2. In designer2 hash table used for id to index search. Our general developer sugest us to use derect index table where id it is index. in case of huge import and for new document we may reorder and rewrite table. It is one-time operation and hash have cost on every transaction.

3. few minor. 
ui.display = ; 
in UIInitialisation() better put in try-catch with errer explanation. On Android inder vnc sever XOpenDisplay(NULL) sometimes failed.
for image update we may use memcpy
---
for (uintptr_t row = 0; row < height; row++) {
      memcpy(destination,source,width);
      source += stride/4;
      destination+=width; 
}
---
4. For asian languages it is need unicide support and text md formating support. Will keep you informed on progress.

5.We add grayscale images support for UIImageDisplay and add UiImage with position and canvas but no zoom for image tables and galleries. Is you need we may send pull request or send you editor code as result.
