### ISSUE TITLE
Essence and Luigi development

### ISSUE THREAD

**Issue by RimeOCRLIB** [nakst/luigi#24]
Good day.

For benefit of Essence development will be useful to rename Luigi to essence_ui.h
The reason is:
1. Essence is the main goal.
2. Luigi is promotion driver and it is need connect it to main brand.
3. Each person are able to remember 200 brands total.

Dear Nakst, which license you have in mind for whole Essence family?

**Comment by nakst** [comment]
They are distinct projects, I am not merging them.
