### ISSUE TITLE
Liugi and Message Passing Interface

### ISSUE THREAD

**Issue by RimeOCRLIB** [nakst/luigi#25]
Good day

What was your inspiration for genious Luigi core messaging system?
https://en.m.wikipedia.org/wiki/Message_Passing_Interface

This system may work as core IPC for OCR training.
May I ask our advice where to read more?

With best regards
Open Source Buddhism Library
Alexander Stroganov

**Comment by nakst** [comment]
My inspiration was from my use of the Win32 message passing system: https://learn.microsoft.com/en-us/windows/win32/api/winuser/nc-winuser-wndproc
I noticed that typically the user wants to be able to override the message for a specific element, which is where the distinction between `messageUser` and `messageClass` came from.
