### ISSUE TITLE
Luigi and Asian languages Xutf8LookupString input

### ISSUE THREAD

**Issue by RimeOCRLIB** [nakst/luigi#26]
Good day.

We have in progress Asian languages input for Luigi.
For now problem is it XLib input for multi-byte characters.
Inside Luigi we are just handle wchar_t instead of char by Freetype (or Pango).
This way we are able to read Xutf8LookupString input for first part of unicode – up to 0x0600 (Arabian) at last.

Problem is we can not fire KeyPeess XEvent by any  keyboard driver upper then 0x0700.
Any advice or idea how handle KeyPress in 0x0f00 - 0xffff (tibetan, sanskrit, japan) ranges in XLib?
May we kindly ask you test Xutf8LookupString and XwcLookupString on your computer for upper unicode ranges?

```
// in
//bool _UIProcessEvent(XEvent *event)

m.textBytes = Xutf8LookupString(window->xic, &event->xkey, text, sizeof(text) - 1, &symbol, &status); 
			
         printf("input utf8:");  
         for(int i=0;i<m.textBytes;i++){        
            printf("%x ",text[i]);       
         }  
         printf("\n");
         
         
         wchar_t textw[32];         
         int wlen=XwcLookupString(window->xic, &event->xkey, textw, sizeof(textw) - 1, &symbol, &status); 
         printf("input utf16:");  
         for(int i=0;i<wlen;i++){        
            printf("%x ",textw[i]);       
         }  
         printf("\n");			
```

**Comment by nakst** [comment]
I do not have an input method editor or keyboard layout setup to test these character ranges. I suggest looking into how SDL2 handles this, maybe they have a solution?

**Comment by RimeOCRLIB** [comment]
This is not problem of x11 or code in Luigi. Under android we use TigerVnc for connect to X11 display. This program are not able send to XLib proper keycode for upper unicode ranges.
