### ISSUE TITLE
FreeType for font rendering (linux)

### ISSUE THREAD

**Issue by rncar** [nakst/luigi#4]
```
gcc -O2 luigi_example.c -lX11 -lm -lfreetype -DUI_FREETYPE `pkg-config --cflags freetype2` -DUI_FONT_PATH=./luculent.ttf -DUI_FONT_SIZE=24
```

The command compiles fine, but the font is the same as without the freetype flags.

Its possible to change the font size of the default X11 (no freetype) font ?
Thanks and cool project.

**Comment by nakst** [comment]
> Its possible to change the font size of the default X11 (no freetype) font ?
This is a bitmap font hard coded into the luigi.h source file, so you'd have to modify that. See here: https://github.com/nakst/luigi/blob/main/luigi.h#L801

> The command compiles fine, but the font is the same as without the freetype flags.
After calling `UIInitialise();`, try putting something like
```c
UIFontActivate(UIFontCreate("/absolute/path/to/font.ttf", 11 /* font size */));
```
Does that make a difference?

**Comment by rncar** [comment]
Yes, its working now. Thanks.
