### ISSUE TITLE
Windows codepath problems

### ISSUE THREAD

**Issue by khvorov45** [nakst/luigi#5]
Compiling with
```
cl -Od -Z7 -nologo -TC ./luigi_example.c -link User32.lib Gdi32.lib Shell32.lib
```
Results in
```
luigi.h(3678): error C2143: syntax error: missing ')' before '*'
luigi.h(3678): error C2059: syntax error: ')'
luigi.h(3678): error C2100: illegal indirection
luigi.h(3678): error C2143: syntax error: missing ')' before ';'
```
The line it's complaining about is
```c
void (*callback)(UIElement *) = va_arg(arguments, void (*)(UIElement *));
```
MSVC doesn't seem to understand a function pointer type without a typedef. I tried changing compiler flags - removing `-TC` adding `-std:c11`, `-std:c17`. It didn't help.

Beyond that, the other problem is that 
```c
_UIInitialiseCommon();
``` 
runs before
```c
ui.heap = GetProcessHeap();
```
But there is a font allocation in `_UIInitialiseCommon` which just crashes since it tries to access `ui.heap`

**Comment by nakst** [comment]
I have made your suggested changes in 79791be, but I do not have currently have a Windows environment to test them on easily. Could you confirm that this is working now?

**Comment by khvorov45** [comment]
Can confirm that it's working now, thanks.
